### ISSUE TITLE
UI: consortia and pipeline view bugs

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1136]
## Expected Behavior
Consortia users are not a part of should not be 'viewable' only joinable if they are not private.

Likewise, on the pipelines page, users should not see pipelines that are not part of their consortium at all unless they are shared pipelines.

## Current Behavior
You can view the details of pipelines and consortia that are not your own.

## Possible Solution
* Remove view details from consortia list, make sure to pair this w/ api checks
* Remove pipelines from list page, again use a filtering api call

**Comment by dylanmartin** [comment]
@rssk When you say "User should only have the consortia that are not their own listed on the page", which page are you referring to?

**Comment by rssk** [comment]
the Consortia list page, I revised the comment because it was sort of nonsense
