### ISSUE TITLE
UI: deleting a pipeline causes ui crash

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1175]
## Expected Behavior
Deleting a pipeline shouldnt crash the UI:0(

## Current Behavior
Deleting a pipeline currently active on a consortium crahes

## Steps to Reproduce
- create a consortium and pipeline that is active
- delete said pipeline
- navigate to the pipelines page on the consortium edit view

# Appendium
deleting a pipeline should also remove the pipeline from a consoritia's active pipeline

**Comment by dylanmartin** [comment]
TypeError: Cannot read properties of undefined (reading 'id') 
 
    in ConsortiumPipeline (created by Mutation)
    in Mutation (created by Apollo(ConsortiumPipeline))
    in Apollo(ConsortiumPipeline) (created by WithStyles(Apollo(ConsortiumPipeline)))
    in WithStyles(Apollo(ConsortiumPipeline)) (created by ConsortiumTabs)
    in div (created by ConsortiumTabs)
    in ConsortiumTabs (created by Mutation)
    in Mutation (created by Apollo(ConsortiumTabs))
    in Apollo(ConsortiumTabs) (created by Mutation)
    in Mutation (created by Apollo(Apollo(ConsortiumTabs)))
    in Apollo(Apollo(ConsortiumTabs)) (created by Mutation)
    in Mutation (created by Apollo(Apollo(Apollo(ConsortiumTabs))))
    in Apollo(Apollo(Apollo(ConsortiumTabs))) (created by Query)
    in Query (created by Apollo(Apollo(Apollo(Apollo(ConsortiumTabs)))))
    in Apollo(Apollo(Apollo(Apollo(ConsortiumTabs)))) (created by Connect(Apollo(Apollo(Apollo(Apollo(ConsortiumTabs))))))
    in Connect(Apollo(Apollo(Apollo(Apollo(ConsortiumTabs))))) (created by WithStyles(Connect(Apollo(Apollo(Apollo(Apollo(ConsortiumTabs)))))))
    in WithStyles(Connect(Apollo(Apollo(Apollo(Apollo(ConsortiumTabs)))))) (created by RouterContext)
    in div (created by RouteContainer)
    in RouteContainer (created by RouterContext)
    in main (created by Dashboard)
    in div (created by Dashboard)
    in div (created by Dashboard)
    in Dashboard (created by ConnectedDashboard)
    in ApolloProvider (created by ConnectedDashboard)
    in ApolloProvider (created by ConnectedDashboard)
    in ConnectedDashboard (created by withRouter(ConnectedDashboard))
    in withRouter(ConnectedDashboard) (created by Connect(withRouter(ConnectedDashboard)))
    in Connect(withRouter(ConnectedDashboard)) (created by RouterContext)
    in ThemeProvider (created by App)
    in div (created by App)
    in ErrorBoundary (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Root)
    in Root
    in Provider
