### ISSUE TITLE
JOIN CONSORTIUM button doesn't work.

### ISSUE THREAD

**Issue by dylanmartin** [MRN-Code/coinstac#1228]
**Describe the bug**
JOIN CONSORTIUM button doesn't work.

**To Reproduce**
1. Start from a fresh devdata
2. Go to the Consortia page
3. Click JOIN CONSORTIUM on Test Consortia 2

**Expected behavior**
Clicking the JOIN CONSORTIUM button should make the user join the consortium

**Screenshots**
![image](https://user-images.githubusercontent.com/7193853/158652986-d0f7d955-480f-45c2-93c3-9b98fc94ea2d.png)

**Comment by rochaeb** [comment]
Thanks @dylanmartin!

This exact bug happened on a call earlier today and your report made it easier for me to reproduce it locally.
