### ISSUE TITLE
Allow selecting all files as a fallback in the file selector

### ISSUE THREAD

**Issue by rochaeb** [MRN-Code/coinstac#1229]
**Describe the bug**
Currently if the compspec asks for a csv file and do not provide the expected extensions we do not allow the user to pick any file.

**To Reproduce**
1. Remove the `extensions` property in the `covariates` input in the `Ridge Regression (Singleshot) - FreeSurfer Volumes` compspec located in `coinstac-api-server/seed/data/coinstac-schema-regression-ss-fsl.json`
2. Create a consortium and pipeline with this computation
3. Try to map data for this field

**Expected behavior**
Add a fallback option so the user can select files from any extension

**Screenshots**
File picker
![Screenshot from 2022-03-17 12-03-10](https://user-images.githubusercontent.com/37052303/158875827-b37ec36d-1b68-4566-a298-fda81f6e7e41.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Version - 6.3.0

**Comment by dylanmartin** [comment]
Does it make sense to just remove the extension filter completely?
https://github.com/trendscenter/coinstac/blob/master/packages/coinstac-ui/app/main/index.js#L678

**Comment by rochaeb** [comment]
I think we'd like to keep the filters because it makes for a better user experience. We could just add a fallback filter called something like `All files` that would allow to pick any file.

**Comment by dylanmartin** [comment]
Also the filters don't seem to work on Windows or Mac. All files are visible on both for me.

**Comment by dylanmartin** [comment]
#1231
