### ISSUE TITLE
Devops: cant access the prod api from the cluster

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1234]
## Current Behavior
Cant talk to the api from the cluster server:(

## Possible Solution
Mess w/ network config in aws

## Steps to Reproduce
ssh into the cluster server and run `curl https://coinstac.rs.gsu.edu/api/version ` observe no connectivity

**Comment by praeducer** [comment]
Kelly needs to run pre-processing. As long as she can get to the API, should be good.

**Comment by praeducer** [comment]
Shoot to finish by mid-next week.

**Comment by praeducer** [comment]
Note that "this is just to get the simulator running on the cluster" per Kelly. She may need additional support following the completion of this task.

**Comment by praeducer** [comment]
Currently setting up VPN so I can access the source server: https://www.infradead.org/openconnect/anyconnect.html

**Comment by praeducer** [comment]
Currently having Selva run the Reachability Analyzer between the two servers. https://us-east-1.console.aws.amazon.com/vpc/home?region=us-east-1#CreateNetworkPath:

**Comment by praeducer** [comment]
Great info per Selva:

> I think Brainforge servers are on GSU ( not on cloud). so the server trendsgndev101 might be a virtual server in GSU.
> yeah I think that is the case.
> 
> [trendsgndev101.rs.gsu.edu](http://trendsgndev101.rs.gsu.edu/) I see this in the other channel
> 
> if this GSU server is trying to reach server-01 (AWS instance), you may want to check if the security group allows the traffic from GSU network range.

**Comment by praeducer** [comment]
I have some concerns the issue may lie on the source server side, which Selva and I don't have control over. I'm going to double check each networking and security layer on the destination/COINSTAC side. After that, we need to find out who manages the source GSU server.

From Selva:
```
outbound rules are normally not restricted. but you may want to understand how the rules are configured in the source server.

I could ping that URL from home network and GSU VPN

it would be good to check if the request from source is reaching the target EC2 instance

for ex: access logs of nginx etc

if the request times out, then its the problem somewhere in the firewall or network settings in cloud.
```

**Comment by praeducer** [comment]
Long term need to migrate some of the other Trends Servers from GSU to our AWS environment.

**Comment by praeducer** [comment]
Moving servers would involve system down time and new domain names.

**Comment by praeducer** [comment]
The source server may have recently moved to AWS.

**Comment by praeducer** [comment]
Could just change the domain names to trends center. Regardless, be best to have them in our network.

The other sys admin might help with migration so he doesn't have to maintain them anyway.

**Comment by hjbockholt** [comment]
What about the extra monthly cost of this?
In general the gsu servers are costing way less

**Comment by praeducer** [comment]
Hey @hjbockholt! This is a good point. We're only in brainstorming mode, so no decisions being made anytime soon. I'm also new here so learning where all these servers live (like on-prem and in the cloud). 

During our discussion, we did bring up cost optimization for sure. For our group, cost would also include labor, which is scarce to be honest. Similarly, talent is hard to hire and get a hold of internally sometimes. Our researchers have constant deadlines to meet. Of course, we also want to be respectful of our grantors. 

I think compute costs would be about the only benefit of keeping them on GSU servers. For us engineers on the ground, we really need to minimize blockers and maximize creative control as much as we can to boost productivity.

If we take this idea seriously, I'd recommend we go through something like a total cost of ownership analysis (as mentioned here, noting the obvious bias: https://aws.amazon.com/economics/). 

**Any other details on the GSU servers that make sense to share here for me to know about?** You can also email me at pprae at gsu dot edu.

**Comment by praeducer** [comment]
Note: I have emailed the potential system admin of the source server for additional guidance.

**Comment by praeducer** [comment]
TODO: check VPC flow logs on destination server side to confirm request isn't even making it to that network at all.

**Comment by praeducer** [comment]
Confirmed the VPC's Network ACLs are all set to defaults per https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html#default-network-acl. That component should not be an issue. Looking for other ACLs that could be blocking as well.

**Comment by praeducer** [comment]
TODO: Run CURL again but to GPU server (a fresh build) to eliminate anything specific to the other destination server.
