### ISSUE TITLE
CI: artifacts not saving

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1281]
## Task Description
CI needs to save artifacts on fails, there are two parts to this
* https://circleci.com/docs/2.0/artifacts/
  present in the config:
```
      - store_artifacts:
          path: /home/circleci/screenshots
 ```
*  and this bit in each e2e test
https://github.com/trendscenter/coinstac/blob/master/packages/coinstac-ui/test/e2e/computation-run-2-members.test.js#L34
  this is likely where the issue is
## Steps to Reproduce
`mkdir ~/screenshots` in your env
Run CI top level
```
# builds the necessary images
./scripts/dockerbuild-for-ci.sh 

# then run
docker-compose up --exit-code-from ui
```
To get a test to purposely fail modify a test to do so (e2e-single is ideal) and then modify this line here
https://github.com/trendscenter/coinstac/blob/master/packages/coinstac-images/coinstac/dockerfiles/Dockerfile-ci-ui#L17
to only be `npm run test:e2e-single` to make the debug process sane

**Comment by dylanmartin** [comment]
After changing the test to e2e-single, then running all 3 commands on a fresh pull of master, the tests fail and there is nothing in the ~/screenshots directory. 

![image](https://user-images.githubusercontent.com/7193853/163606416-f2aa6b51-975e-4221-8d5c-25e2f68c2441.png)
