### ISSUE TITLE
UI: remove docker requirement for headless pipelines

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1284]
## Task Description
Remove docker requirement, or make it less intrusive for headless pipelines. This means no error notifications on pipeline save of image not being able to be downloaded or any other excessive UI noise from docker errors. It would also be nice to have the docker image download also triggered if you select yourself on the active user list

## Steps to Reproduce
Create a headless pipeline and observe the docker download

**Comment by praeducer** [comment]
Is this related to https://github.com/trendscenter/coinstac/issues/1262?

**Comment by rssk** [comment]
@praeducer yes it seems to be a duplicate :3

@kalitopix another place that needs fixing is the computation page tries to loop through some list from the docker api (i assume) and throws an error
