### ISSUE TITLE
UI: site has incorrect data mapping when adding members to consortia

### ISSUE THREAD

**Issue by rochaeb** [MRN-Code/coinstac#1298]
**Describe the bug**

**To Reproduce**
1. test3 joins the consortia, maps data
2. test2 starts, it runs fine and finishes
3. test2 changes someting in input fields, saves pipeline and hit run
4. Error shows up saying some field is missing from computation.

**Expected behavior**
Keep data mapping when the changes in the pipeline were only on owner fields

**Comment by praeducer** [comment]
@rssk would like @dylanmartin  inspect this at some point.

**Comment by dylanmartin** [comment]
@rochaeb Could you clarify the steps to reproduce?
I'm guessing test3 and test2 are users.
Who creates the consortium originally?
does step #2 mean that test2 is an owner of the consortium and that they start a run?
does step #3 happen after the first run and before the second?
Where does this error show up?
When you say "test2 changes someting in input fields, saves pipeline and hit run" does that mean a value in the computation step gets changed?
@rssk

**Comment by dylanmartin** [comment]
This process yielded no funkiness:

test1: create a consortium
test1: Select SSR-FSL
test1: map the data
test2: join the consortium
test1: check to see if mapping is still good
test2: map data
test1: check to see if mapping is still good
test1: change the computation fields
— I changed the ROIs - nothing happened
— Changing the covariates did undo mapping for respective columns as expected.
test1: check mapping
test2: check mapping
