### ISSUE TITLE
UI: refreshing the UI starts suspended pipelines

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1304]
## Task Description
Refreshing the UI (eg: cmd+r) causes a suspended pipeline to be erroneously restarted

## Steps to Reproduce
* run a pipeline
* suspend
* refresh and relogin

**Comment by rochaeb** [comment]
I believe this was resolved. You can run into this issue only if the run was not properly suspended and as such has not been stored in localstorage as a suspended run.
