### ISSUE TITLE
#UI change: Computations page

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1348]
![Image](https://user-images.githubusercontent.com/5415931/170528661-e626ed7e-1025-4cbd-80bd-60512ce11806.png)

Under the View github project page button: https://github.com/trendscenter/coinstac-brainage-fnc
Under the View test data button: https://github.com/trendscenter/coinstac-brainage-fnc/tree/main/test/input

Please adjust the font etc. the pic is just for reference

**Comment by rssk** [comment]
# task
add two new buttons referencing the screenshot
* one for the project page `meta.repository`
* one for the test data, a new field that may not exist for all computations so should be `meta.repository || meta.testData`

**Comment by spanta28** [comment]
These buttons should exist for all computations. Once you create the page, I can give you the links for those for each computation.

**Comment by spanta28** [comment]
Here is the spreadsheet for all computations info. The computations that are not included in this will be hidden from users, so no need to put this buttons for them. 

[computations_info.xlsx](https://github.com/trendscenter/coinstac/files/8827844/computations_info.xlsx)
