### ISSUE TITLE
Pipeline: fix end file transfer 

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1350]
## Task Description
When on the final round trip, as in the remote as declared 'success', the files from the remote to the outer nodes are not tied to any  promise/await and as such are unable to be guaranteed to be done at the end of the pipeline promise

## Task Notes
* Tie file transfer into the pipeline promise, allowing the UI/etc to know that files are done
* look here https://github.com/trendscenter/coinstac/blob/master/packages/coinstac-pipeline/src/setup-outer.js#L404

## Steps to Reproduce
Run any pipeline (modify large file test? in `packages/coinstac-images`) with large files and observe the file system vs end difference

**Comment by rssk** [comment]
Note: looking through the code this _might_ be fixed, but I'm unclear, this is easiest to get breaking using a dev/prod build as files have to traverse the network

**Comment by dylanmartin** [comment]
The code does look like it handles this case but it's worth checking.

Can I get more explicit details on reproducing the error? 
* Which computation steps should I use?
* What indicates the pipeline is done?
* What indicates that the upload is done?
  * Should I add console logs to these events to capture the timeline?
