### ISSUE TITLE
Vault: upload artifacts to s3

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1351]
## Task Description
Vault runs without the user who is running the vault do not have access to files created on the vault server.

In a 'vault only run' with a computation that outputs file artifacts (vbm), those files are only available on the vault server. After a pipeline finishes these should be available (via the api) to anyone who has permissions to them.

## Task Notes
* change headless to vault in packaing and docs :), also change `cloud` to`vault` for naming sanity
* run a vault client run with VBM (stats) this will give you file output on finish
* on vault client finish (on a run with only vault clients??) upload everything in the `output/` dir to s3, using runid as a lookup key
* delete these artifacts locally on successful upload
* make an api call to store these in the db, perhaps in the run table?
* proxy the s3 download through hapi, there are some examples of this online (they might be express but it should be roughly the same), this puts access control to the s3 buckets in the hands of the api
* make a front end for this, likely somewhere w the `view results` button on the results page and widgets

**Comment by dylanmartin** [comment]
Here's an outline of the sequence of events we want to happen:

1. Identify when a consortia is running a pipeline with vault users only.
2. Designate one of the vault clients to upload its final files
3. Have the final files uploaded to s3 through the COINSTAC API
4. Save the links to those s3 files in the COINSTAC database
5. Allow certain users to access those files through the API

**Comment by dylanmartin** [comment]
Creating an S3 proxy on the API server seems like a good place to start

**Comment by praeducer** [comment]
@dylanmartin where is the other task we were working on and how does it relate to this one? I'm assuming this is for the overall system you are building. May want to link them and describe the differences.

**Comment by dylanmartin** [comment]
The other issue we were working on was here: https://github.com/trendscenter/coinstac/issues/1358
This issue (#1351) is the parent task of the other issue #1358, which we kind of turned into a bigger task

**Comment by dylanmartin** [comment]
The code is in a merge-able state.
The remaining tasks are these:
* change headless to vault in packaing and docs :), also change cloud to vault for naming sanity
* make a front end for this, likely somewhere w the view results button on the results page and widgets
