### ISSUE TITLE
UI: download and display s3 vault data

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1366]
## Task Description
When a vault run has no normal users, the vault will upload the results to s3. The UI then needs to grab and unpack this for the user

## Task Notes
* download the resource based on the `runid` - this may not be available yet while it upload
* the `open local results` button should be `download results` if its a vault only run
* unpack the results as if there were normal results eg `COINSTAC_HOME/consortiumID/runID/{results}`
* the results page may need some work to not crash if the results are not available (before download)

**Comment by dylanmartin** [comment]
Will need to add state to the `run` document. "has-downloadable-files", "file-upload-complete"

**Comment by rssk** [comment]
other things to think about
* wiring up a subcription on the run doc to update the button state (results uploading to ready to download?)
* the download button should change to the normal 'view files' button if 
   ) 1 its not a vault only run (so normal)
   ) 2 it is but there are no files (read; run doc says so)
   ) 3 there are files but they are there locally (you could check the file system orrrr save something in local state, up to you, 
      the later may run afoul if the user deletes the files etc)
