### ISSUE TITLE
UI: cleanup vbm 'data' section left over from ssr

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1378]
## Task Description
The vbm-regression comspec has an unnecessary field `data`, remove it and see what breaks:)

**Comment by hvgazula** [comment]
I suggest removing Single-shot Regression altogether.

**Comment by spanta28** [comment]
Can we make this change in the "Regression - VBM" soon. It is confusing to end users, they would think its Freesurfer data while its VBM. Basically to make sure code does not break, we can just include a default ROI like datatype "nifti" and "Brain-Stem" and simply hide the Output Datatype field for "Regression - VBM" pipeline.
