### ISSUE TITLE
UI: add singularity support

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1384]
## Task Description
Singularity is mostly supported by the backend, make changes to the UI to support it on the frontend

## Task Notes
The largest difference between docker and singularity will be how they store images, singularity does have an open source 'hub' but image management locally is largely left up to the end user.

* first step will be creating a place for the images to live on disc `COINSTAC_HOME/singularityImages`
* Integrate singularity images into the `pull` images UI component this will use spawn to execute the command line interface eg:
`singularity pull  library://coinstac/computations/ssr-fsl:latest`. This command will have to be put into `coinstac-manager`'s singularity type class

**Comment by dylanmartin** [comment]
Currently, the Singularity service provider does not have a `pull` method. An analogous `pull` method to the docker service method needs to be created.

https://docs.sylabs.io/guides/3.2/user-guide/cli/singularity_pull.html

![image](https://user-images.githubusercontent.com/7193853/179271312-af197537-4cbd-4147-8239-1a8d4d19ea9c.png)

**Comment by dylanmartin** [comment]
To answer:
Where should the singularity image directory exist on the file system?
Where should that path be defined in the application?
