### ISSUE TITLE
Identify research journals for Vault paper

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1395]

**Comment by dylanmartin** [comment]
This seems like a useful tool
https://journalfinder.elsevier.com/

**Comment by dylanmartin** [comment]
It seems like we have decided on the Journal: Frontiers in Neuroinformatics

**Comment by hvgazula** [comment]
I have no say in this, but I will still throw in my left-over cents :). https://www.springer.com/journal/12021
