### ISSUE TITLE
coinstac.org chrome issue "Places using coinstac"

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1439]
![issue](https://user-images.githubusercontent.com/5415931/186010251-e6fe2168-da3f-4607-b548-ff2615e33c14.png)
On chrome its still showing the issue.

**Comment by pixelsaurus** [comment]
I use Chrome. Shift+Command+R

**Comment by spanta28** [comment]
Great. I forget the hard refresh sometimes!
