### ISSUE TITLE
Trends VBM vault results do not show locally

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1444]
<img width="1223" alt="Screen Shot 2022-08-24 at 10 11 07 PM" src="https://user-images.githubusercontent.com/5415931/186573111-c82b46ed-d0db-416c-b37d-a8bc277b7672.png">

Images view /Open results does not work

Can we remove the "Images view" under the results because by default it shows the images or the stats so it looks redundant, unless I am misunderstanding the logic here.

**Comment by pixelsaurus** [comment]
Something still isn’t working quite right. 

You should see an image under each header and the generated image files if you click on “Open Local Results”

**Comment by dylanmartin** [comment]
@spanta28 Can you look in your coinstac folder to see if those files exist locally?
If this was a Vault-only run then a "download results" button should have appeared on the top right.
We could check the mongodb to see if the run document has the flags for uploading and downloading assets.
@rssk I don't know off the top of my head how to access the prod database.

**Comment by dylanmartin** [comment]
The latest run assets in the s3 bucket are from July 22
![image](https://user-images.githubusercontent.com/7193853/186722667-e2b5cdbb-ba97-459e-a71d-09abb26201f6.png)

**Comment by spanta28** [comment]
@dylanmartin There are no outputs created in the coinstac/output folder. the "open results" button does not do anything when I click on it.

**Comment by dylanmartin** [comment]
Is this a vault-only run? There are no assets from this run in the s3 bucket

**Comment by spanta28** [comment]
yes

**Comment by dylanmartin** [comment]
@rssk this is solved by #1449 correct?

**Comment by rssk** [comment]
I dont think so, I think this is a specific issue only with @spanta28
