### ISSUE TITLE
Automapping on UI mapping page causes covariates to disappear

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1468]

**Comment by kalitopix** [comment]
@praeducer Could you please add the steps to reproduce this bug?
Video attachment is better.

**Comment by spanta28** [comment]
@rssk if you could post the video here for Xiao.

**Comment by kalitopix** [comment]
https://user-images.githubusercontent.com/48020962/192888948-beb6dece-3f40-4498-ba25-70696fe7ef10.mov
