### ISSUE TITLE
Admin tool for user account management

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1471]

**Comment by rssk** [comment]
There is no way besides direct manipulation to change any user account data, add a admin page to do so

* create a tab in the new `Admin` page for `User Accounts`
* show a list of users and allow their details to be edited. This might be achieved by having a list of users as expandable tabs that turn into the JSON doc that is the user data, with save button on editing. The computation page has a similar feature for compspec editing, take a look there

* move the other two pages mentioned to other tabs on the `Admin` page

**Comment by rssk** [comment]
Also, in doing this we should consolidate the admin pages (permissions, pipeline states) to tabs on this page with the user crud being a tab as well
