### ISSUE TITLE
Update green arrow checkbox icon to more accurately describe state on Covariate page

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1473]
When errors are thrown, it still shows a confirmation 

Related task:

- [ ] https://github.com/trendscenter/coinstac/issues/1472

**Comment by rssk** [comment]
So upon closer inspection this is actually the file import check, there might be a better way to display this so it doesnt confuse however

**Comment by dylanmartin** [comment]
#1525
