### ISSUE TITLE
Trends Freesurfer vault update

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1488]
## Task Description
Remove "Trends Freesurfer Cobre Desikan vault" and "Trends Freesurfer Cobre Destrieux vault" from COINSTAC and add this new merged Vault instead. 

New of the Vault : TRENDS_COBRE_FreeSurfer_VAULT
Vault data here on CMI ec2 instance:
/home/rkelly/Vault_data/TRENDS_COBRE_FreeSurfer_VAULT

Updated ROI's list:
/home/rkelly/Vault_data/ROI_categorization_COINSTAC/all_ROIs.txt

## Task Notes
We may categorize the ROI's /tag them based on their affiliation to the respective atlas, like users could select "all_desikan_roi's" etc. and run regression. I will discuss with Vince on that and update.

**Comment by rssk** [comment]
Done, what do I need the ROI list for exactly?

**Comment by spanta28** [comment]
Its to populate this list as shown in the pic. 
<img width="1039" alt="Screen Shot 2022-09-29 at 8 29 26 AM" src="https://user-images.githubusercontent.com/5415931/193059316-cbe91440-7153-48fa-9885-9b96039fd633.png">

**Comment by spanta28** [comment]
BTW I noticed the "TReNDS COBRE FreeSurfer Vault" in the latest COINSTAC prod and gave it a try. If I tried with single ROI or 2 ROI's it worked fine. But If I selected "All Interests" then it throws an error.
<div class="MuiPaper-root jss1187 MuiPaper-elevation1 MuiPaper-rounded" style="box-sizing: inherit; color: rgba(0, 0, 0, 0.87); transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; background-color: rgb(255, 255, 255); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px; display: flex; padding: 16px 24px; margin-top: 16px; font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.14994px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Results Object:
--
null
*Output Type not defined in Compspec.

</div><div class="MuiPaper-root jss1187 jss1193 MuiPaper-elevation1 MuiPaper-rounded" style="box-sizing: inherit; color: red; transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; background-color: rgb(255, 255, 255); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px; display: flex; padding: 16px 24px; margin-top: 16px; font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.14994px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">"Pipeline error from pipeline 6335ad7f1b282a216c65b49b user: TReNDS COBRE FreeSurfer Vault\n Error details: Unexpected token N in JSON at position 22554\n Additional computation failure information:\n\n Error code: 0\n\n Stderr: /usr/local/lib/python3.7/site-packages/sklearn/feature_extraction/image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n dtype=np.int):\n/usr/local/lib/python3.7/site-packages/nilearn/datasets/__init__.py:90: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.\n \"Numpy arrays.\", FutureWarning)\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n eps=np.finfo(np.float).eps,\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:836: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n eps=np.finfo(np.float).eps, positive=False):\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1097: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1344: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1480: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n eps=np.finfo(np.float).eps, copy_X=True, positive=False):\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:152: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n precompute=False, eps=np.finfo(np.float).eps,\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:320: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n eps=np.finfo(np.float).eps, random_state=None,\n/usr/local/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:580: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n eps=4 * np.finfo(np.float).eps, n_jobs=None,\n/usr/local/lib/python3.7/site-packages/sklearn/decomposition/online_lda.py:31: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations\n EPS = np.finfo(np.float).eps\n\n "</div>

**Comment by spanta28** [comment]
The ROI's list is not updated as of now. Please update 
https://github.com/trendscenter/coinstac/blob/master/packages/coinstac-ui/app/common/utils/freesurfer-predictors.js

based on /home/rkelly/Vault_data/ROI_categorization_COINSTAC/all_ROIs.txt
on the CMI ec2 instance

**Comment by rssk** [comment]
all updated
