### ISSUE TITLE
UI: Deal with when CSVs have columns with missing data elements 

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1519]
## Task Description
If a csv has rows with missing data, casting fails. It makes sense to catch these and remove them from the parsed csv

## Task Notes
* errors on casting are already caught, create a list of caught subjects from this
* remove those rows (this may be naturally happening via the catching)
* have the UI show a dialog with the removed subjects, extra credit: add the reason, this may not be useful to the user though or easy to figure out
* add this dialog above `Map CSV columns to pipeline variables` and below the show files dialog box
<img width="1121" alt="Screen Shot 2022-10-04 at 5 19 05 PM" src="https://user-images.githubusercontent.com/5331533/193931695-b85ed77c-8440-4d31-a77a-90f862fc67cb.png">

**Comment by dylanmartin** [comment]
I'm trying to reproduce the bug but haven't gotten there yet. The mapping succeeds. Should I try to run the computation?
EDIT: Nevermind. I didn't hit save.

Here's a test .csv I'm using:
![image](https://user-images.githubusercontent.com/7193853/194116507-0ad3fde2-cae4-468b-b3d4-9f5fbf6033a9.png)

Maybe I'm missing something when creating the compspec and input map:
![image](https://user-images.githubusercontent.com/7193853/194116663-fc437645-1f21-4ee0-9c07-2c9f4db944d8.png)

**Comment by dylanmartin** [comment]
The error I am getting is different than the one displayed above:
![image](https://user-images.githubusercontent.com/7193853/194117151-a9f15b3f-5b54-4b0a-b761-393d2f05a7d1.png)
