### ISSUE TITLE
TRENDS GICA Vault upload

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1530]
## Task Description
Upload the GICA Vault data from [here](https://mygsu-my.sharepoint.com/:f:/g/personal/spanta_gsu_edu1/Ej_FukhUKt1EiOoApESkTBUB-sDOpc4VLzaTIvhjENSY7A?email=rkelly30%40gsu.edu&e=gVneLw)

## Task Notes

The computation that it will be connected to is "Decentralized Mancova"
Here is the inputspec.json file with the default settings
[settings.txt](https://github.com/trendscenter/coinstac/files/9734784/settings.txt)

If its possible to put the options in the file here as defaults (point the "GICA input directory" to the Vault data), that would be great because we know these options work for sure.  

Javier will get access to NYU server and integrate the Vault.

**Comment by rssk** [comment]
Yeah this needs development time, as well as I dont really understand the data in the sharepoint, doesnt match the csv
