### ISSUE TITLE
Add "String" to the Covariate datatypes for Regression Freesurfer volumes

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1562]
<img width="1012" alt="Screen Shot 2022-11-04 at 8 05 26 PM" src="https://user-images.githubusercontent.com/5415931/200096335-64af8daa-ab43-411b-bee0-e7f01c5c4c2f.png">

**Comment by spanta28** [comment]
Once this is fixed , please Send updated inputspec.json to @hvgazula

**Comment by pixelsaurus** [comment]
Just have to add it in that “data” array in the compspec

**Comment by pixelsaurus** [comment]
See: https://github.com/trendscenter/coinstac-regression-vbm/blob/master/compspec.json

**Comment by pixelsaurus** [comment]
"covariates": {
        "label": "Covariates",
        "type": "csv",
       "items": ["boolean", "number", "string"],
        "source": "member"
      },

**Comment by spanta28** [comment]
Harsh mentioned he needs to talk to Ross last we spoke about this. He said he needs to update the parser to read data types accurately from covariates.

**Comment by hvgazula** [comment]
Done https://github.com/trendscenter/coinstac-regression-fsl/pull/22
