### ISSUE TITLE
Update fsl parser to reflect new inputspec

### ISSUE THREAD

**Issue by hvgazula** [MRN-Code/coinstac#1563]
Depends on https://github.com/trendscenter/coinstac/issues/1562

**Comment by pixelsaurus** [comment]
https://github.com/trendscenter/coinstac-msr-fsl/blob/master/compspec.json

**Comment by pixelsaurus** [comment]
Are you working on VBM Regresion or MSR FSL?

The screengrab that Sandeep provided is for MSR FSL.

**Comment by pixelsaurus** [comment]
Updated inputspec for msr-fsl.

**Comment by hvgazula** [comment]
Awesome, thanks. Please ignore my e-mail about inputspec for
coinstac-regression-fsl. I will take care of it myself.
