### ISSUE TITLE
My consortium no longer appears to work

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1608]
## Task Description
The consortium one is an owner/member off no longer appear to be at the top of the consortia list page in a their specific section

## Task Notes
There used to be a specific section at the top before all the other consortia denoting ones that you were a member of

**Comment by kalitopix** [comment]
@rssk I can see my consortia on the consortia list page.
<img width="2297" alt="Screenshot 2022-12-23 at 3 50 46 AM" src="https://user-images.githubusercontent.com/48020962/209304471-1300416c-13e9-411a-8e47-77d29513796e.png">

**Comment by praeducer** [comment]
Need to find a way to paginate. Xiao found a bug when creating 100 users.

![Image](https://user-images.githubusercontent.com/4081511/213761823-f5cc89cf-aaf8-426a-a0f1-1e26e1569d4c.png)

**Comment by praeducer** [comment]
Make sure separation shows on latest release.

**Comment by praeducer** [comment]
Solve freezing and stuttering first. Need to make sure all the elements are rendering.

**Comment by praeducer** [comment]
Related to https://github.com/trendscenter/coinstac/issues/1632
