### ISSUE TITLE
Error rendering freesurfer regression output in the UI

### ISSUE THREAD

**Issue by hvgazula** [MRN-Code/coinstac#1610]
**Describe the bug**
Freesurfer Regression output on COINSTAC has an extra (duplicate) _t_-value.

**To Reproduce**
Please discuss this with @spanta28 

**Expected behavior**
There should be one _t_-value corresponding to each covariate.

**Screenshots**
![image](https://user-images.githubusercontent.com/9400767/208216640-1dc0911c-3d4b-49a8-a953-ad23b89f3843.png)

**Desktop (please complete the following information):**
- Got the error snapshot from @spanta28 and @sunithabasodi  

**Additional context**
I tried a similar (maybe not exact data) freesurfer regression in the simulator and I don't see any extra _t_-value suggesting the error could be on the UI side. (see below for an example)

![image](https://user-images.githubusercontent.com/9400767/208216782-f1154db0-eb99-447c-ac85-fa2af7926f13.png)

**Comment by hvgazula** [comment]
@spanta28 Please assign this issue to the appropriate assignee. Thanks.

**Comment by spanta28** [comment]
Javier should be able to track it down. I will assign it to him.

**Comment by spanta28** [comment]
@pixelsaurus please take a look at this when you get a chance
