### ISSUE TITLE
Write "Contribution to the field statement" for Frontiers Vault paper submission

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1627]
When you submit your manuscript, you will be required to briefly summarize in 200 words your manuscript's contribution to, and position in, the existing literature in your field. This should be written avoiding any technical language or non-standard acronyms. The aim should be to convey the meaning and importance of this research to a non-expert.

While Frontiers evaluates articles using objective criteria, rather than impact or novelty, your statement should frame the question(s) you have addressed in your work in the context of the current body of knowledge, providing evidence that the findings – whether positive or negative – contribute to progress in your research discipline. This will help the chief editors to determine whether your manuscript fits within the scope of a specialty as defined in its mission statement; a detailed statement will also facilitate the identification of the editors and reviewers most appropriate to evaluate your work, ultimately expediting your manuscript's initial consideration.

Example statement on: Markram K and Markram H (2010) The Intense World Theory – a unifying theory of the neurobiology of autism. Front. Hum. Neurosci. 4:224. doi: 10.3389/fnhum.2010.00224

Autism spectrum disorders are a group of neurodevelopmental disorders that affect up to 1 in 100 individuals. People with autism display an array of symptoms encompassing emotional processing, sociability, perception and memory, and present as uniquely as the individual. No theory has suggested a single underlying neuropathology to account for these diverse symptoms. The Intense World Theory, proposed here, describes a unifying pathology producing the wide spectrum of manifestations observed in autists. This theory focuses on the neocortex, fundamental for higher cognitive functions, and the limbic system, key for processing emotions and social signals. Drawing on discoveries in animal models and neuroimaging studies in individuals with autism, we propose how a combination of genetics, toxin exposure and/or environmental stress could produce hyper-reactivity and hyper-plasticity in the microcircuits involved with perception, attention, memory and emotionality. These hyper-functioning circuits will eventually come to dominate their neighbors, leading to hyper-sensitivity to incoming stimuli, over-specialization in tasks and a hyper-preference syndrome. We make the case that this theory of enhanced brain function in autism explains many of the varied past results and resolves conflicting findings and views and makes some testable experimental predictions.

https://www.frontiersin.org/guidelines/author-guidelines

**Comment by krootesmurdy** [comment]
this will be adapted from our abstract.

**Comment by dylanmartin** [comment]
Neuroimaging research faces numerous challenges, including technological, policy, administrative, and methodological barriers that hinder collaboration and data sharing.
COINSTAC is an already established open-source platform that advances open science by streamlining federated analyses and facilitating seamless integration of modular computations. This study presents the new COINSTAC Vaults (CVs), an enhancement to the COINSTAC platform, which addresses the current challenges of the field by offering standardized, persistent, and highly-available datasets, integrating seamlessly with federated analysis capabilities. In this paper, we demonstrate the impact of CVs through several studies utilizing federated analysis, showcasing their potential to improve the reproducibility of research and increase sample sizes in neuroimaging studies. COINSTAC Vaults improve the reproducibility of research and enable larger sample sizes in neuroimaging studies. Unlike traditional data sharing platforms, CVs facilitate federated learning, ensuring privacy protection and fostering asynchronous collaboration between institutions. By offering easy access to public datasets and secure contributions from private dataset owners, CVs promote open science and data-driven discovery.
