### ISSUE TITLE
Finalize Vault paper title

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1643]

**Comment by praeducer** [comment]
![Image](https://user-images.githubusercontent.com/4081511/214925731-f0ac37f6-e832-4f7f-93a5-fdd231bc72e7.png)

**Comment by praeducer** [comment]
We may be able to borrow some vocabulary and thoughts on how Vaults integrate with the greater ecosystem here: https://oreoni.github.io/04/data.html

![Image](https://user-images.githubusercontent.com/4081511/214956282-30c488a0-a73f-4b94-98fa-643e9edbae1d.png)

**Comment by praeducer** [comment]
Make sure COINSTAC is in the title.

**Comment by praeducer** [comment]
COINSTAC Vaults: Towards a more complete neuroimaging ecosystem

**Comment by hvgazula** [comment]
If this is the final title, I recommend removing "more". 😄 It's either complete or incomplete. No more no less. ;)

**Comment by dylanmartin** [comment]
Enhancing Collaborative Neuroimaging Research: Introducing COINSTAC Vaults for Federated Analysis and Reproducibility
