### ISSUE TITLE
Make sure paper is properly cited

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1668]
- [ ] Original COINSTAC papers
- [ ] Shore up the introduction
- [ ] Cite all quantifiers or facts
- [ ] Something historical as in a thing that was done or an event that occurred. 
- [ ] Any paragraph that has no citations. This may also indicate the paragraph is not "scientific" enough. 
- [ ] Tech stack like AWS, S3, Python, Docker etc.
- [ ] COBRE data studies and data sets

You can't cite too much!

If you can't cite it, it may need to be restated.

Anything not cited should be new information we are presenting or discovered. Another type is common knowledge.

**Comment by praeducer** [comment]
here's the list for reference on general COINSTAC/Federated Learning overview in (more-or-less) chronological order:
https://www.frontiersin.org/articles/10.3389/fnins.2016.00365/full
https://europepmc.org/article/ppr/ppr41189
https://ieeexplore.ieee.org/abstract/document/7953372?casa_token=Zhqz19UqroYAAAAA:5_Fw8aY_P1wJDjs6bUeKc7kVx-gvGlPU6D4T4OcXe6xVOFejtKV9p9GqSKfCe7sXqEpcOLW0uw
https://joss.theoj.org/papers/10.21105/joss.02166
https://www.sciencedirect.com/science/article/pii/S0165027019302754?casa_token=3c_Ey5E5LgsAAAAA:8zZhjrtlEAQ_DnqTTc30owtzNCmD-IyOqGbdU7kK3ngtp9wGsMUOO0blju_hL4ucHxNSBI_7S1c
https://link.springer.com/article/10.1007/s12021-021-09550-7
https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.25788
https://link.springer.com/article/10.1007/s12021-021-09559-y

**Comment by praeducer** [comment]
![image](https://user-images.githubusercontent.com/4081511/219440388-1b24337b-d511-4262-8f3e-a9b369218461.png)

We could probably put some citations from Anand on Differential Privacy in COINSTAC as well

**Comment by adsarwate** [comment]
If you search for a paper in scholar.google.com, click on "Cite" and then "BibTeX" you can cut and paste the bibtex into the .bib file on the overleaf.
