### ISSUE TITLE
Add feature for directory mapping

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1673]

**Comment by praeducer** [comment]
Put in next release.

**Comment by pixelsaurus** [comment]
Please use dpica for testing: https://github.com/trendscenter/coinstac-dpica

**Comment by pixelsaurus** [comment]
Recent commit here: https://github.com/trendscenter/coinstac/commit/124f8fdabd5fa18663b89c557a538ef81337479f
