### ISSUE TITLE
Speak to differential privacy in the Vault paper

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1688]
Discuss in sections:
- policy and privacy
- discussion and future work

Mention:
- In limitations section, consider writing something about the ability to recreate the source data using only derived results. It is a security limitation that people could recreate the data. 
- Multi-party computation in future work

**Comment by adsarwate** [comment]
I added some paragraphs and a bunch of references into the paper on overleaf. Not quite sure what you want for future work.
