### ISSUE TITLE
workshop bugs: Remove the docker not connected error message, because the docker status already shows red or green circle

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1781]
Remove the docker not connected error message, because the docker status already shows red or green circle

**Comment by pixelsaurus** [comment]
@rssk Was this already done? I'm testing in dev and not getting the UI toast notification.

**Comment by rssk** [comment]
I sort of thought so, but also saw it in person so im unsure whats going on

**Comment by rssk** [comment]
come to think of it, this might be my fault, i sort of remember rerouting some docker error output in `main/index.js` take a look at the blame hist there and see if theres anything
