### ISSUE TITLE
workshop bugs: GICA vault results page refresh issues

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1782]
The 'Download results' button does not show up until I logout login. And after I click 'download results', the results dont show up in iframe until I , go to other tabs and come back. Video attached. 

https://github.com/trendscenter/coinstac/assets/5415931/43f3ad97-56c3-45ca-9a96-ac865dae1557

**Comment by rssk** [comment]
The iframe on this page isnt rerendering once the results get downloaded
