### ISSUE TITLE
ROI's being wiped out when clicked "Save" pipeline setup

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1852]
This happens on the first time consortia and pipeline are setup.. Everything including ROI's are setup and , user goes to the top and clicks "save" and then ROI's disappear. Second time on ROI's get saved just fine. Videos attached here:

https://github.com/trendscenter/coinstac/assets/5415931/d2101377-7491-4129-9912-4f2437543895

https://github.com/trendscenter/coinstac/assets/5415931/11187f7a-0b81-40f1-bef6-3e9b93fca78a

**Comment by kalitopix** [comment]
@spanta28 This is no longer reproducible. Seems like it's fixed a while ago.

**Comment by rssk** [comment]
CNR
