### ISSUE TITLE
Improve UI for entering data

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1924]
Some of the computations have this editable field, but it is not very responsive, if you try to type in it quickly it takes the cursor to the beginning etc. and the UI is not intuitive enough for new user for editing like user does not recognize its editable field sometimes.

Some computations have this like 'Regression (Multishot) - CSV' and 'fMRI Preprocessing Pipeline with NiFTI support', please check the snapshots and see how you can improve this.
<img width="628" alt="Screenshot 2024-04-16 at 10 19 57 PM" src="https://github.com/trendscenter/coinstac/assets/5415931/6d97882b-c9be-44bb-bcb3-ddc16d4289aa">
<img width="514" alt="Screenshot 2024-04-16 at 10 18 42 PM" src="https://github.com/trendscenter/coinstac/assets/5415931/e64d0115-13a8-4eb8-b408-30c5531a9bfb">
<img width="581" alt="Screenshot 2024-04-16 at 10 18 35 PM" src="https://github.com/trendscenter/coinstac/assets/5415931/f073d9eb-c0ff-4402-a66a-5398795c66a2">

**Comment by spanta28** [comment]
Xiao said : we are using other json viewer library called react-json-view to show the compspec but only for viewing purpose.
this library provides editing feature too.
https://mac-s-g.github.io/react-json-view/demo/dist/
please check and let me know if it’s fine to use editing feature of this library for pipeline steps.

@pixelsaurus can you comment on this?

**Comment by pixelsaurus** [comment]
Xiao is confusing the compspec view in "Computations" for a defined Object
field in the "Pipeline" editor field.

It is indeed editable, but is a little brittle when it comes to editing.

Here's an alternative: https://www.npmjs.com/package/jsoneditor-react

**Comment by kalitopix** [comment]
@pixelsaurus Okay
